on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    name: Run existing tests
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.11, 3.12, 3.13]
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup system
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb libxkbcommon-x11-0 libegl1-mesa-dev
      - uses: actions/checkout@v4
      - name: Install package
        run: pip install ".[all]" && pip install pyside6 pytest-xvfb
      - name: Run pytest
        run: pytest -vvv -s --no-qt-log
